export const CONTACT_DETAILS_DATA = [
  {
    id: 1,
    firstName: "Ronald",
    lastName: "Richards",
    email: "albert@borer.com",
    role: "Admin",
    createdAt: "Feb 15, 2021",
  },
  {
    id: 2,
    firstName: "Jacob",
    lastName: "Jones",
    email: "albert@borer.com",
    role: "Admin",
    createdAt: "Feb 15, 2021",
  },
  {
    id: 3,
    firstName: "Ronald",
    lastName: "Richards",
    email: "albert@borer.com",
    role: "Admin",
    createdAt: "Feb 15, 2021",
  },
  {
    id: 4,
    firstName: "Jacob",
    lastName: "Jones",
    email: "albert@borer.com",
    role: "Admin",
    createdAt: "Feb 15, 2021",
  },
  {
    id: 5,
    firstName: "Ronald",
    lastName: "Richards",
    email: "albert@borer.com",
    role: "Admin",
    createdAt: "Feb 15, 2021",
  },
  {
    id: 6,
    firstName: "Jacob",
    lastName: "Jones",
    email: "albert@borer.com",
    role: "Admin",
    createdAt: "Feb 15, 2021",
  },
  {
    id: 7,
    firstName: "Ronald",
    lastName: "Richards",
    email: "albert@borer.com",
    role: "Admin",
    createdAt: "Feb 15, 2021",
  },
  {
    id: 8,
    firstName: "Jacob",
    lastName: "Jones",
    email: "albert@borer.com",
    role: "Admin",
    createdAt: "Feb 15, 2021",
  },
  {
    id: 9,
    firstName: "Ronald",
    lastName: "Richards",
    email: "albert@borer.com",
    role: "Admin",
    createdAt: "Feb 15, 2021",
  },
];
